repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
      args: [--line-length=120]
    python_version: python3.5
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
-   repo: https://github.com/PaddlePaddle/clang-format-pre-commit-hook
    rev: HEAD
    hooks:
    -   id: clang-formater
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.0.dev1
    hooks:
        - id: pylint
